global using Xunit;
global using FitnessApi.Models;
global using FitnessApi.Data.Interfaces;
global using FitnessApi.Dtos;
global using FitnessApi.Data.Repositories;
global using FitnessApi.Infrastructure;
global using FitnessApi.Controllers;
global using FitnessApi.Profiles;
global using AutoMapper;